// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package datetimeutilities.actions;

import java.util.Calendar;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Get Month of the year
 */
public class MonthOfYear extends CustomJavaAction<java.lang.Long>
{
	public MonthOfYear(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		Calendar calendar = Calendar.getInstance();
		int MonthofYear = calendar.get(Calendar.DAY_OF_MONTH);
		Long MonthofYear_Long = (long) MonthofYear;
		return MonthofYear_Long;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "MonthOfYear";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
