// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package datetimeutilities.actions;

import java.util.Calendar;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Get the total weeks in year using year value
 */
public class TotalWeeksinYear extends CustomJavaAction<java.lang.Long>
{
	private java.lang.Long Year;

	public TotalWeeksinYear(IContext context, java.lang.Long Year)
	{
		super(context);
		this.Year = Year;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		int yr = Year.intValue();
		Calendar calendar = Calendar.getInstance();
		calendar.set(yr, 1, 1);
		long WeekOfYear = calendar.getActualMaximum(Calendar.WEEK_OF_YEAR);
		return WeekOfYear;
		
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "TotalWeeksinYear";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
